@startuml

skinparam ParticipantFontColor automatic

title: CAS 9 refus de la résolution par l'OI

autonumber

participant OC #Blue
participant OI #Green

OI->OI: je dépose la pièce jointe
OI->OI: HTTP 201 indentifiant de la pj.
OI->OI: je crée la malfaçon \n POST /malfaçon
OI->OI: HTTP 201 indentifiant de la malfaçon
OI->OI: je crée le trouble ticket malfaçon \n POST /troubleTicket {\n"ticketType": "malfaçon",\n"description": "<description ici>",\n"relatedEntity":[{"href":"<référence de la malfaçon chez l'OI>","id":"<idMalfacon>"}],\n"priority": "High",\n"requestedResolutionDate": "<horodatage>",\n"severity": "normal"}, \n"attachment":";{"href":"<référence de la pièce jointe chez l'OI>","id":"<idPJ>"}"

OI->OI: contrôles de surface

OI->OI: acquitement technique du dépot de ticket \n http201"troubleTicket": \n{"ID":"100", "href":"https://myOI.com:8080/tmf-api/troubleTicket/v4/troubleTicket/100", "Status":"acknoledged"}

OI->OI: [ALT] abonnement aux notifications TT (n'est pas nécessaire à chaque ticket) \n POST https:\//myOI.com:8080/tmf-api/troubleTicket/v4/troubleTicket/hub?Accept:application/json,{"callback":"http://OI.in.listner.com"}

OI->OI: acquitement de la souscription (avec son ID) \n http201:"Created, Content-Type: application/json, Location: /troubleTicket/hub/42{"id":"42","callback":"http://OI.in.listner.com","query":null}"


OI->OI: contrôler l'accessibilité de la pj. et la recevabilité du ticket

OI->OI: acquitement fonctionnel du dépot de ticket (inProgress) \n { "eventId":"00002", "eventTime":"<horodatage>", "eventType":"TroubleTicketStatusChangeEvent", "event": \n{ "troubleTicket": \n{"ID":"100", "href":"https://myOI.com:8080/tmf-api/troubleTicket/v4/troubleTicket/100", "troubleTicketTicketStatusType":"inProgress"}\n} \n}

OI->OI: rechercher les id de tickets encours pour cet OC sur ce PM (seront ajoutés en référence à ce ticket)
OI->OI: pour chaque ticket identifié, ajouter la référence de ce ticket au troubleTicketRelationship[1] des tickets identifiés
OI->OI: pour ce ticket, ajouter les références des tickets en troubleTicketRelationship[1,n]

OI->OI: j'identifie l'OC responsable

OI->OC: je crée un trouble ticket malfaçon chez l'OC en lien avec le ticket OI \n POST /troubleTicket {\n"ticketType": "malfaçon",\n"description": "<description ici>",\n"externalId": "100",\n"href":"https://myOI.com:8080/tmf-api/troubleTicket/v4/troubleTicket/100",\n"id":"100",\n"priority": "High",\n"requestedResolutionDate":"<date>",\n"severity": "normal",\n"relatedEntity":[{"href":"référence de la malfaçon chez l'OI","id":"<idMafaçon>"};{"href":"référence de la pièce jointe chez l'OI","id":"<idPJ>"}]

OC->OC: contrôles de surface

OC->OI: acquitement technique du dépot de ticket \n http201"troubleTicket": \n{"ID":"1000", "href":"https://myOC.com:8080/tmf-api/troubleTicket/v4/troubleTicket/1000", "Status":"acknoledged"}

OI->OC: [ALT] abonnement aux notifications TT (n'est pas nécessaire à chaque ticket) \n POST https:\//myOC.com:8080/tmf-api/troubleTicket/v4/troubleTicket/hub?Accept:application/json,{"callback":"http://OI.in.listner.com"}

OC->OI: acquitement de la souscription (avec son ID) \n http201:"Created, Content-Type: application/json, Location: /troubleTicket/hub/42{"id":"42","callback":"http://OC.in.listner.com","query":null}"


OC->OI: contrôler l'accessibilité de la pj. et la recevabilité du ticket

OC->OI: acquitement fonctionnel du dépot de ticket (inProgress) \n { "eventId":"00002", "eventTime":"<horodatage>", "eventType":"TroubleTicketStatusChangeEvent", "event": \n{ "troubleTicket": \n{"ID":"1000", "href":"https://myOC.com:8080/tmf-api/troubleTicket/v4/troubleTicket/1000", "troubleTicketTicketStatusType":"inProgress"}\n} \n}

OC->OC: résolu, défaut corrigé \n PATCH /troubleTicket {\n"ID":"1000",\n"troubleTicketTicketStatusType":"resolved",\n"statusChangeDate":"<horodatage>",\n"statusChangeReason":"<motif résolution>"}

OC->OI: notification de résolution: \n { "eventId":"00003", "eventTime":<horodatage>, "eventType":"TroubleTicketResolvedEvent", "event": \n{ "troubleTicket": \n{"ID":"1000", "href":"https://myOC.com:8080/tmf-api/troubleTicket/v4/troubleTicket/1000", "troubleTicketTicketStatusType":"resolved"}\n} \n}


OI->OI: soumission de résolution \n PATCH /troubleTicket {\n"ID":"100",\n"troubleTicketTicketStatusType":"resolved",\n"statusChangeDate":"<horodatage>",\n"statusChangeReason":"résolution soumise"}
OI->OC: notification de résolution: \n { "eventId":<eventId>, "eventTime":"<horodatage>", "eventType":"TroubleTicketResolvedEvent", "event": \n{ "troubleTicket": \n{"ID":"100", "href":"https://myOI.com:8080/tmf-api/troubleTicket/v4/troubleTicket/100", "troubleTicketTicketStatusType":"resolved"}\n} \n}
OI->OI: contrôle de la résolution
OI->OI: refus de la résolution \n PATCH /troubleTicket {\n"ID":"100",\n"troubleTicketTicketStatusType":"held",\n"statusChangeDate":"<horodatage>",\n"statusChangeReason":"<résolution réfusée par l'OI>, "note":{"string":<explication du refus de résolution>}}

OI->OC: notification du refus de résolution : \n { "eventId":"00003", "eventTime":"<horodatage>", "eventType":"TroubleTicketStatusChangeEvent", "event": \n{ "troubleTicket": \n{"ID":"100", "href":"https://myOI.com:8080/tmf-api/troubleTicket/v4/troubleTicket/100", "troubleTicketTicketStatusType":"held", "note":{"string":<explication du refus de résolution>}}\n} \n}


OC->OC: prendre en compte le refus de la résolution  \n PATCH /troubleTicket {\n"ID":"1000",\n"troubleTicketTicketStatusType":"held",\n"statusChangeDate":"<horodatage>",\n"statusChangeReason":"cloture contradictoire refusée"}

OC->OI: notification d'acquitement de refus de cloture : \n { "eventId":<eventId>, "eventTime":"<horodatage>", "eventType":"TroubleTicketResolvedEvent", "event": \n{ "troubleTicket": \n{"ID":"1000", "href":"https://myOC.com:8080/tmf-api/troubleTicket/v4/troubleTicket/1000", "troubleTicketTicketStatusType":"held"}\n} \n}

OC->OI: // suite du cas métier selon le contexte:\n -cf. dépassement de délai \n ou \n -cf. complément information OC->OI




@enduml
